### ISSUE TITLE
Compile error when 12th bit of an immediate value is set

### ISSUE THREAD

**Issue by nishtahir** [racerxdl/riscv-online-asm#2]
Running this instruction seems to generate a compile error

```
addi x1, x0, 2048

file.s: Assembler messages:
file.s:6: Error: illegal operands `addi x1,x0,2048'
```

However,  running this seems to work just fine.
```
addi x1, x0, 1024

OK!
```

I could be wrong, but I believe the immediate value should be 12 bits long.

**Comment by racerxdl** [comment]
You're correct, indeed it has 12 bit, but its a sign extended imediate value, so the range is - 2048 to 2047

**Comment by nishtahir** [comment]
Oh, I see. I forgot that the assembly value is signed. Thanks for clearing that up for me 😄.
