### ISSUE TITLE
Loads wrong addresses

### ISSUE THREAD

**Issue by Jar0T** [racerxdl/riscv-online-asm#3]
Using:
la t0, <label>
always results in:
auipc t0, 0
addi t0, t0, 0
By which it sets t0 to current PC and it should set it to address of <label>

**Comment by racerxdl** [comment]
Do you have a full example?

Technically the code is located fixed at address 0x0, thats why it changes to 0.

**Comment by Jar0T** [comment]
```
.global _boot
.text

_boot:
    addi x1, x0, 100
    la x2, temp
    
.data
temp:
	.byte 10
```
This code results in loading address of `la x2, temp` instead of `temp`

**Comment by racerxdl** [comment]
Just found the issue. I need to specify a linker script, otherwise it defaults to linux one, which expects linux-ld to fill the section offsets. I'm updating the tool with the fixes :D

**Comment by racerxdl** [comment]
Now it generates correctly: 
![image](https://github.com/racerxdl/riscv-online-asm/assets/578310/e61fdbb0-3830-4596-8ffc-7395a52d1818)

And you can change the real offsets in the linker script :D
